#Resource Icon, AppIcon, "drive.ico"

#Resource VersionInfo
#Resource FileVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0
#Resource ProductVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0

#Resource StringInfo "0407", "04B0"

#Resource Version$ "CompanyName",      "BasicAware"
#Resource Version$ "FileDescription",  "Renames any file as yyyymmdd"
#Resource Version$ "LegalCopyright",   "Copyright 2002-2016 BasicAware"
#Resource Version$ "OriginalFilename", "RENToday.exe"
#Resource Version$ "ProductName",      "RENToday"
#Resource Version$ "ProductVersion",   "1.5.0.0"
#Resource Version$ "FileVersion",      "1.5.0.0"
#Resource Version$ "Comments",         "Written by Knuth Konrad"

$COMPANY_NAME = "BasicAware"
